repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: check-ast
    -   id: check-docstring-first
    -   id: check-toml
    -   id: check-vcs-permalinks
    -   id: check-yaml
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.1.3
    hooks:
    -   id: python-safety-dependencies-check
-   repo: https://github.com/timothycrosley/isort
    rev: 5.3.2
    hooks:
    -   id: isort
